sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
      env:
        - EXECUTE_COVERAGE=true
        - MEASURE_COVERAGE=true

notifications:
  email: false

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - mkdir -p ./build/logs || return 0

install:
  - make install

script:
  # PHPUnit
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then make report-coverage ; fi
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then make test ; fi

after_script:
  - if [[ MEASURE_COVERAGE == 'true' ]]; then upload-coverage ; fi
